/** List of predefined activities members can participate in. The "other" option is presented at runtime. */
export const activityList = [
    'Balance & Strength class',
    'Basketball (youth)',
    'Basketball (adult)',
    'Coffee after Mass',
    'CPR review class',
    'English Cenacle',
    'First Aid Review class',
    'Fly Fishing',
    'Futsal soccer',
    'Heat Volleyball',
    'Home School',
    'Knight of Columbus',
    'Ladies Auxiliary',
    'Line Dancing',
    'Lit. and Bible Study',
    'OCIA',
    'OTHER',
    'Mahjong',
    'Pickleball',
    'Ping Pong',
    'Soccer (youth)',
    'Soul Core',
    'Spanish Cenacle',
    'Youth Irish Dance',
    'Youth Jazz Dance',
    'Youth Group',
    'Volleyball',
    'Walking Track (indoor)',
    'Walking Club (outdoor) & core',
    'Women\'s Bible Study',
    'Women\'s Gospel Encounter'
];
