import type { ManagedNotification } from '@/utility/types/components/NotificationManager';
import { createContext } from 'react';

/** Structure of the data that is passed to all child props from the NotificationManager context. */
interface NotificationManagerContextValue {
    /** ID generated by React's useId hook for the toaster component. */
    'toasterId': string;
    /**
     * Creates a new notification and adds it to the managed notification list.
     * @param config Configuration object for the new notification, excluding the ID.
     * @returns The ID of the newly created notification.
     */
    'newNotification': (config: Omit<ManagedNotification, 'id'>) => ManagedNotification['id'];
    /**
     * Removes a notification from the managed notification list based on its ID.
     * @param id ID of the notification to be removed.
     * @returns Void.
     */
    'removeNotification': (id: ManagedNotification['id']) => void;
    /**
     * Updates an existing notification in the managed notification list.
     * @param id ID of the notification to be updated.
     * @param updatedConfig Partial configuration object containing the properties to be updated.
     * @returns The ID of the updated notification object.
     */
    'setNotification': (id: ManagedNotification['id'], updatedConfig: Partial<Omit<ManagedNotification, 'id'>>) => ManagedNotification['id'];
}

/** Context for the NotificationManager, providing access to notification-related functionality. */
export const NotificationManagerContext = createContext<NotificationManagerContextValue>({
    /**
     * Placeholder function used in the context of the NotificationManager before it is properly initialized.
     * @returns Place holder for the ID of the newly created notification.
     */
    'newNotification': () => 'Not Initialized!',
    /**
     * Placeholder function used in the context of the NotificationManager before it is properly initialized.
     * @returns Nothing.
     */
    'removeNotification': () => void 0,
    /**
     * Placeholder function used in the context of the NotificationManager before it is properly initialized.
     * @returns Place holder for the ID of the updated notification object.
     */
    'setNotification': () => 'Not Initialized!',
    'toasterId': '61579379-a2e6-4aa1-9d07-7a4294ff7299'
});
